// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmF2taY-Xlg9TIVLb4G-jBoSegfLi0qQ',
    appId: '1:362751064279:web:4b08e006f82838b73cd892',
    messagingSenderId: '362751064279',
    projectId: 'instagram-login-e7cfa',
    authDomain: 'instagram-login-e7cfa.firebaseapp.com',
    storageBucket: 'instagram-login-e7cfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDA4ATlo3mog-S-8EpwyQHeimhZM3ZE8',
    appId: '1:362751064279:android:532fbfc610ce6bff3cd892',
    messagingSenderId: '362751064279',
    projectId: 'instagram-login-e7cfa',
    storageBucket: 'instagram-login-e7cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5nM5azl3QIAW1SbBzyYIdzjNibSjPmg',
    appId: '1:362751064279:ios:d8467fff354f27bb3cd892',
    messagingSenderId: '362751064279',
    projectId: 'instagram-login-e7cfa',
    storageBucket: 'instagram-login-e7cfa.appspot.com',
    iosClientId: '362751064279-qfak2slf4k2e0q3efmhjlffl4tbm2135.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramLogin',
  );
}
